### ISSUE TITLE
[HANDLING] Discuss and adapt handling of "DefSiegeEngineGoldThreshold"

### ISSUE THREAD

**Issue by TheRedDaemon** [UnofficialCrusaderPatch/extension-aicloader#2]
Krarilotus:
> This value sets the amount of gold the AI needs to have before it can make defensive siege engines.
> The catch is, its actually the negative of that. So if you set -150, the AI needs 150 gold, and if you set 150, the AI can cheat up to 150 gold when setting up defensive siege engines in a loop (setting up more siege engines than it has gold for and then the gold is reset to 0 afterwards and the dept is gone)

There are different ways to handle this:
* Simply allowing the range to be the full signed int range, simply allowing the the old and the new negative numbers. (*)
* Invert the numbers before writing the values. Maybe still increase the range? (*)
* Handle the change not here, but invert the logic in a small fix module.
* Other?

The intended solution and its effect on existing AIs still needs to be discussed.

(*) These would need checks how the integer writes are currently handled. (Are negative values are even properly supported?)

**Comment by TheRedDaemon** [comment]
@Krarilotus Any preference regarding the solution?

**Comment by Krarilotus** [comment]
I would opt for inverting the value, making the value to set semantically identical with its meaning. That could be done by flipping the value at 0.

Then i would also let all integer values just going through to the game as they were before, as the game interprets them as signed. So you can set negative values until half of max int and positive until half of maxint - 1.

So basically just the behaviour inverted at 0 (flip + and minus) for the GoldSiegeThreshold and everything else stays as it was in ucp 2.15

**Comment by gynt** [comment]
What about changing the game logic at this location to make everything work more sensibly? The aicloader can include the small fix I think

**Comment by TheRedDaemon** [comment]
@gynt Well, inverting the value and inverting the usage do basically the same. Inverting the written value however can easily be supported within the "framework" of the aicloader and does not need some separate logic that changes stuff of the game code. If this value is only used at one point, the only special benefit of changing the games logic I see would be if another party reads this AIC value, since they would need to know that it works differently, and the case seems unlikely....  
At the moment changing the value before being written appears to be the least invasive action, for me at least.

@Krarilotus Can you provide some examples for values and how they should be changed? Because reading your text it sounds like I should write 100 still as 100 in one part and the other sounds like it should be written as -100.

**Comment by Krarilotus** [comment]
So how i view it, right now its like this:
People so that AIs won't cheat setup -150 so the AI will need at least 150 gold before setting up siege engines defensively. Or say -500 so it will need 500 gold.
They setup say 1000 so they can cheat siege engines defensively up to a total value of 1000 at a time (basically going to -1000 dept, but the dept is erased instantly, not sure why tho)

Wished behaviour:
Write 150 so the AI will need 150 gold or say 500 gold so it needs 500 gold before the AI will make siege engines, so the name is the same as its semantic meaning: Gold Recruit Threshold
But we still want the option for the AI to still cheat stuff, like with -1000 it can go to that -1000 dept cheating defensive siege engines for free

For the Beer for example, or the stone and stuff that has maximum values, the AI can also be created to be super lucrative and cheating gold by setting them negative, so they should have this value possible to set in the AIC at least even if people won't use it much, they have the option. Here though, the value won't need to be inverted, but support the negative values too (selling 7 beer to get to 0 beer, like a true mathematician hehehe).
